/*
 * Generated by ISE 22.05.10.6292 - macosx-x86-64
 */

#include "eif_eiffel.h"
#include "eif_project.h"
#include "egc_include.h"

#ifdef __cplusplus
extern "C" {
#endif
extern void F1_23();
extern EIF_REFERENCE F1_14();
extern void F267_7781();
extern void F269_7943();
extern void F267_7785();
extern void F270_8011();
extern void F272_8175();
extern void F270_8016();
extern void F343_3870();
extern void F297_7627();
extern void F93_1939();
extern EIF_REFERENCE F93_1926();
extern EIF_BOOLEAN F93_1938();
extern EIF_BOOLEAN F93_1946();
extern void F93_1948();
extern void F93_1949();
extern void F93_1950();
extern void F73_1706();
extern EIF_TYPED_VALUE F73_1707();

long *eif_area_table = (long *)0;
long *eif_lower_table = (long *)0;


extern void egc_init_plug (void); 
void egc_init_plug (void)
{
	egc_prof_enabled = (EIF_INTEGER) 0;
	egc_correct_mismatch = (void (*)(EIF_REFERENCE)) F1_23;
	egc_twin = (EIF_TYPED_VALUE (*)(EIF_REFERENCE)) F1_14;
	egc_strmake = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F267_7781;
	egc_immstr8make_from_c_byte_array = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F267_7785;
	egc_str32make = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F270_8011;
	egc_immstr32make_from_c_byte_array = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F270_8016;
	egc_arrmake = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F343_3870;
	egc_strset = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F269_7943;
	egc_str32set = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F272_8175;
	egc_routdisp_wb = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F297_7627;
	egc_is_scoop_capable = 0;
	egc_set_exception_data = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F93_1939;
	egc_set_last_exception = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F93_1938;
	egc_last_exception = (EIF_TYPED_VALUE (*)(EIF_REFERENCE)) F93_1926;
	egc_is_code_ignored = (EIF_TYPED_VALUE (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F93_1946;
	egc_once_raise = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F93_1948;
	egc_init_exception_manager = (void (*)(EIF_REFERENCE)) F93_1949;
	egc_free_preallocated_trace = (void (*)(EIF_REFERENCE)) F93_1950;

	egc_str_dtype = 268;

	egc_immstr8_dtype = 267;

	egc_str32_dtype = 271;

	egc_immstr32_dtype = 270;
	egc_arr_dtype = 342;
	egc_tup_dtype = 217;
	egc_disp_rout_id = 3560;
	egc_copy_rout_id = 18;
	egc_is_equal_rout_id = 11;

	egc_sp_char = 0x02BA;
	egc_sp_wchar = 0x01D2;
	egc_sp_bool = 0x03AA;
	egc_sp_uint8 = 0x01E7;
	egc_sp_uint16 = 0x0385;
	egc_sp_uint32 = 0x0227;
	egc_sp_uint64 = 0x01AD;
	egc_sp_int8 = 0x033D;
	egc_sp_int16 = 0x0319;
	egc_sp_int32 = 0x01A3;
	egc_sp_int64 = 0x0361;
	egc_sp_real32 = 0x02D1;
	egc_sp_real64 = 0x02F5;
	egc_sp_pointer = 0x02AE;
	egc_sp_ref = 0x0159;

	egc_uint8_dtype = 243;
	egc_uint16_dtype = 240;
	egc_uint32_dtype = 237;
	egc_uint64_dtype = 234;
	egc_int8_dtype = 231;
	egc_int16_dtype = 228;
	egc_int32_dtype = 225;
	egc_int64_dtype = 222;
	egc_bool_dtype = 258;
	egc_real32_dtype = 246;
	egc_char_dtype = 255;
	egc_wchar_dtype = 252;
	egc_real64_dtype = 249;
	egc_point_dtype = 261;

	egc_exception_dtype = 110;
	egc_except_emnger_dtype = 92;

	egc_ce_type = egc_ce_type_init;

	egc_ce_exp_type = egc_ce_exp_type_init;
	egc_fsystem = egc_fsystem_init;
	egc_system_mod_init = egc_system_mod_init_init;
	egc_partab = egc_partab_init;
	egc_partab_size = egc_partab_size_init;
	egc_foption = egc_foption_init;
	egc_frozen = egc_frozen_init;
	egc_fpatidtab = egc_fpatidtab_init;
	egc_address_table = egc_address_table_init;
	egc_fpattern = egc_fpattern_init;

	egc_einit = egc_einit_init;
	egc_tabinit = egc_tabinit_init;
	egc_forg_table = egc_forg_table_init;

	egc_system_name = "jj_sha_without_genericity_demo";
	egc_system_location = "/Users/jjj/jj_github/jj_sha/demo/EIFGENs/jj_sha_without_genericity_demo/W_code";
	egc_compiler_tag = 39;
	egc_project_version = 1769055259;
	egc_has_old_special_semantic = 0;
	egc_has_ieee_semantic = 1;
	scount = 1000;

	egc_rcount = 3;
	egc_ridx = 0;
	egc_rlist = (char**) eif_malloc (sizeof(char*)*egc_rcount);
	egc_rcdt = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rcrid = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rcarg = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rlist[0] = "SHA_DEMO.make";
	egc_rcdt[0] = 0;
	egc_rcrid[0] = 2833;
	egc_rcarg[0] = 0;
	
	egc_rlist[1] = "EQA_EVALUATOR.make";
	egc_rcdt[1] = 0;
	egc_rcrid[1] = 2779;
	egc_rcarg[1] = 0;
	
	egc_rlist[2] = "ITP_INTERPRETER.execute";
	egc_rcdt[2] = 0;
	egc_rcrid[2] = 6234;
	egc_rcarg[2] = 0;
	
	
	egc_platform_level = 0x00000D00;
	egc_rt_extension_dt = 72;
	egc_rt_extension_notify = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F73_1706;
	egc_rt_extension_notify_argument = (EIF_TYPED_VALUE (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F73_1707;
}

void egc_rcdt_init (void)
{
	if (egc_rcdt[0] == 0) {
		egc_rcdt[0] = 178; /* SHA_DEMO */
	}if (egc_rcdt[1] == 0) {
		egc_rcdt[1] = 175; /* EQA_EVALUATOR */
	}if (egc_rcdt[2] == 0) {
		egc_rcdt[2] = 289; /* ITP_INTERPRETER */
	}
}

#ifdef __cplusplus
}
#endif
